# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 079658c515895f38c12b5a7945bbc8ab4ed245979bcf08bd43d1dee183535c54b73f9cce828ea37ecf5fc55ff9d5807ced6e2a776a1d1c99829af94d7e3a4b68

test:
  secret_key_base: a8b5fa9a8568e531f559c708aebae29c15f9e570de07e4c1aafa9503e79ada7beaa12aaa10867ebdbe0070f4e67beb946ca3eb810397c3df67def81c259face2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
